# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
method: timestamp
tasks:
  lint:
    desc: Lint with ruff
    sources:
      - src/**/*.py
      - tests/**/*.py
    cmds:
      - uv run ruff check --fix .

  format:
    desc: Format with ruff
    sources:
      - src/**/*.py
      - tests/**/*.py
    cmds:
      - uv run ruff format .

  isort:
    desc: Sort imports with ruff
    sources:
      - src/**/*.py
      - tests/**/*.py
    cmds:
      - uv run ruff check --select I --fix .

  typecheck:
    desc: Check types with ty
    sources:
      - src/**/*.py
      - tests/**/*.py
    cmds:
      - uv run ty check

  sync:
    desc: Install dependencies
    sources:
      - pyproject.toml
    generates:
      - uv.lock
    cmds:
      - uv sync

  serve:
    desc: Start local dev server with hot reload
    cmds:
      - uv run uvicorn mentyx.main:app --host 0.0.0.0 --port 8000 --reload
    deps:
      - sync

  test:
    desc: Run tests on memory database
    env:
      DATABASE_URL: "sqlite+aiosqlite:///:memory:"
    cmds:
      - uv run pytest

  test-postgres:
    desc: Run tests against a real, docker Postgres
    dotenv: [".env"]
    cmds:
      - export DATABASE_URL="postgresql+asyncpg://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME"
      - docker compose up -d db
      - defer: docker compose stop db
      - uv run pytest

  build:
    desc: Build the Docker image
    env:
      BUILD_PYTHON_VERSION:
        sh: grep -v '^#' .python-version
      DEBIAN_DISTRIBUTION: "trixie"
    cmds:
      - docker compose build --build-arg PYTHON_VERSION=${BUILD_PYTHON_VERSION} --build-arg DEBIAN_DISTRIBUTION=${DEBIAN_DISTRIBUTION} backend

  up:
    desc: Build and start the backend with Docker
    cmds:
      - task: build
      - docker compose up -d

  down:
    desc: Stop the backend container
    cmds:
      - docker compose down
